path = {
    'login-btn': "#login-button",
    'log': "input.btn-head",
    'logo': "div.nav_logo",
    'alert-box': "span.weekend-trading-close",
    'add-mov': "span.open-dialog-icon.svg-icon-holder",
    'search-box': "div.searchbox input",
    'first-res': "div.results.scrollable-holder > div",
    'sell-btn': "div#orderdialog div.tradebox-button.tradebox-sell",
    'buy-btn': "div#orderdialog div.tradebox-button.tradebox-buy",
    'quantity': "div.quantity-slider-input-wrapper > input",
    'limit-gain-unit': "input#uniqName_1_10",
    'limit-gain-value': "input#uniqName_1_9",
    'limit-loss-unit': "input#uniqName_1_14",
    'limit-loss-value': "input#uniqName_1_13",
    'confirm-btn': "div.orderdialog-confirm-button",
    'data-table': "tbody.table-body.dataTable-show-currentprice-arrows",
}

symbols = {
    'BTCUSD': "bitcoin",
    'ETHUSD': "ethereum",
    'EURJPG': "eur/jpg",
    'EURUSD': "eur/usd",
    'XAUUSD': "gold",
    '#QMSEP17': "oil",
    '$GERMAN30': "german30",
    'BMW': "bmw",
    'ENEL': "enel",
}